using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UniversityManagementSystem.Model
{
    public class BaseModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public Guid GlobalId { get; set; } = Guid.NewGuid();
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public int UpdatedOn { get; set; }
        public DateTime DeletedAt { get; set; }
        public int CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public int DeletedOn { get; set; }
        public int DeletedBy { get; set; }
    }
}


//We will have the BaseModel class which will be inherited by every child class having following features:

//1.Id(Int type, Autogenerated from db and must be unique means the primary key)
//2.IsActive(bool type)
//3.GlobalId(Guid type)
//4.CreatedAt(datetime type)
//5.UpdatedAt(datetime type)
//6.DeletedAt(datetime type)
//7.CreatedBy(int type)
//8.UpdatedBy(int type)
//9.DeletedBy(int type)
